# Generated by Django 5.0.4 on 2024-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="salary",
        ),
        migrations.AddField(
            model_name="customer",
            name="class_of_garbage",
            field=models.CharField(
                choices=[("1", "plastic"), ("2", "glass"), ("3", "metal")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(default="null", upload_to="images/"),
            preserve_default=False,
        ),
    ]
