# Generated by Django 5.0.4 on 2024-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoAPI", "0002_remove_customer_age_remove_customer_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="class_of_garbage",
            field=models.IntegerField(
                choices=[(1, "plastic"), (2, "glass"), (3, "metal")]
            ),
        ),
    ]
